# Generated by Django 5.0.1 on 2024-01-10 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='candi_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, null=True)),
                ('city', models.CharField(max_length=24, null=True)),
                ('job_desc', models.CharField(max_length=24, null=True)),
                ('doj', models.DateField(null=True)),
                ('status', models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Reject', 'Reject'), ('interviewed', 'interviewed'), ('--', '--')], default='--', max_length=12, null=True)),
            ],
        ),
    ]
