# Generated by Django 5.0.1 on 2024-01-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='register_emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
                ('user_name', models.CharField(max_length=24)),
                ('password', models.CharField(max_length=24)),
                ('role', models.IntegerField(choices=[(0, 'super_admin'), (1, 'admin'), (2, 'manager'), (3, 'operation'), (4, 'hr'), (5, 'agent')], default=0)),
            ],
        ),
    ]
