# Generated by Django 5.0.1 on 2024-01-11 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0006_alter_register_emp_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_emp',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('manager', 'manager'), ('operation', 'operation'), ('super_admin', 'super_admin'), ('agent', 'agent'), ('hr', 'hr')], max_length=24),
        ),
    ]
