# Generated by Django 5.0.1 on 2024-01-12 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0007_alter_register_emp_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_emp',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='register_emp',
            name='blood_group',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='register_emp',
            name='contact',
            field=models.CharField(default='', max_length=24),
        ),
        migrations.AddField(
            model_name='register_emp',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='register_emp',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('manager', 'manager'), ('operation', 'operation'), ('super_admin', 'super_admin'), ('agent', 'agent'), ('hr', 'hr')], default='agent', max_length=24),
        ),
    ]
