# Generated by Django 5.0.1 on 2024-01-15 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0008_register_emp_address_register_emp_blood_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='u_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=24)),
                ('email', models.CharField(max_length=24)),
                ('password', models.CharField(max_length=24)),
            ],
        ),
    ]
