# Generated by Django 5.0.1 on 2024-01-15 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0009_u_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candi_form',
            old_name='city',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='candi_form',
            old_name='job_desc',
            new_name='agent_name',
        ),
        migrations.RenameField(
            model_name='candi_form',
            old_name='doj',
            new_name='dob',
        ),
        migrations.RemoveField(
            model_name='candi_form',
            name='status',
        ),
        migrations.AddField(
            model_name='candi_form',
            name='contact',
            field=models.CharField(max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='candi_form',
            name='inusurance_id',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='candi_form',
            name='remark',
            field=models.CharField(blank=True, default='', max_length=45, null=True),
        ),
    ]
