# Generated by Django 5.0.1 on 2024-01-16 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0010_rename_city_candi_form_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candi_form',
            name='m_file',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='candi_form',
            name='inusurance_id',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='candi_form',
            name='remark',
            field=models.CharField(default='', max_length=45, null=True),
        ),
    ]
