# Generated by Django 5.0.1 on 2024-01-16 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0011_candi_form_m_file_alter_candi_form_inusurance_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candi_form',
            name='status',
            field=models.TextField(default='', null=True),
        ),
    ]
